# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dropZeroElementsXYWin <- function(win, xin, yin) {
    .Call('tPACE_dropZeroElementsXYWin', PACKAGE = 'tPACE', win, xin, yin)
}

interp2lin <- function(xin, yin, zin, xou, you) {
    .Call('tPACE_interp2lin', PACKAGE = 'tPACE', xin, yin, zin, xou, you)
}

Rlwls1d <- function(bw, kernel_type, win, xin, yin, xout, npoly = 1L, nder = 0L) {
    .Call('tPACE_Rlwls1d', PACKAGE = 'tPACE', bw, kernel_type, win, xin, yin, xout, npoly, nder)
}

Rmullwlsk <- function(bw, kernel_type, tPairs, cxxn, win, xgrid, ygrid, bwCheck) {
    .Call('tPACE_Rmullwlsk', PACKAGE = 'tPACE', bw, kernel_type, tPairs, cxxn, win, xgrid, ygrid, bwCheck)
}

Rrotatedmullwlsk <- function(bw, kernel_type, tPairs, cxxn, win, xygrid, npoly, bwCheck) {
    .Call('tPACE_Rrotatedmullwlsk', PACKAGE = 'tPACE', bw, kernel_type, tPairs, cxxn, win, xygrid, npoly, bwCheck)
}

trapzRcpp <- function(X, Y) {
    .Call('tPACE_trapzRcpp', PACKAGE = 'tPACE', X, Y)
}

